import { useId, type CSSProperties } from "react";

/**
 * Shared chart plumbing, ported from final/charts.js `_defs`. Every chart draws with the same
 * gradients and patterns; ids get a per-instance suffix so several charts can share a page.
 */

export type DefName = "lit" | "hot" | "dim" | "dimdown" | "loss" | "hatch" | "stripe" | "glow";

/** A per-instance suffix that is safe inside `url(#…)` (useId's own punctuation is not).
 *  A caller-supplied `uid` (stable across renders and snapshots) takes precedence. */
export function useChartUid(uid?: string): string {
  const auto = useId();
  return (uid ?? auto).replace(/[^A-Za-z0-9]/g, "");
}

/** `url(#lit<uid>)` */
export const ref = (name: DefName, uid: string) => `url(#${name}${uid})`;

/** Per-index kinds: an array from a view model, or a function as in the mockup call sites. */
export type Kinds<K extends string> = readonly K[] | ((i: number) => K);
export const kindAt = <K extends string>(k: Kinds<K> | undefined, i: number, fallback: K): K =>
  (k == null ? undefined : typeof k === "function" ? k(i) : k[i]) ?? fallback;

/**
 * Every chart is either labelled or explicitly decorative; leaving out both is a type error.
 * - `label`: the data in words, generated by the caller from the view model. The wrapper gets
 *   role="img" + aria-label, as in the mockups.
 * - `decorative`: only where the surrounding text already carries the meaning (the rail in the
 *   glass rail box, whose header, ends and knob caption are visible text). No role, no label.
 */
export type ChartA11y = { label: string; decorative?: never } | { decorative: true; label?: never };

/** The wrapper the mockups put around each chart; the SVG itself is always aria-hidden. */
export type ChartFrameProps = ChartA11y & {
  /** Replaces the chart's default wrapper class (e.g. `wave-mob` instead of `wave-desk`). */
  className?: string;
  /** Appended to the wrapper class (default or `className`), e.g. `trips` → `rail trips`. */
  extraClass?: string;
  style?: CSSProperties;
  /** Stable suffix for the gradient/pattern ids; defaults to React's useId. */
  uid?: string;
};

export function frameProps({ label, className, extraClass, style }: ChartFrameProps, defaultClass: string) {
  const base = className ?? defaultClass;
  return {
    className: extraClass ? `${base} ${extraClass}` : base,
    style,
    ...(label ? { role: "img" as const, "aria-label": label } : {}),
  };
}

const stop = (offset: string, color: string) => <stop offset={offset} style={{ stopColor: color }} />;

/** charts.js `_defs(id)`, verbatim. */
export function ChartDefs({ uid }: { uid: string }) {
  return (
    <defs>
      <linearGradient id={`lit${uid}`} x1="0" y1="1" x2="0" y2="0">
        {stop("0", "var(--lamp-deep)")}
        {stop(".62", "var(--lamp)")}
        {stop("1", "var(--cream)")}
      </linearGradient>
      <linearGradient id={`hot${uid}`} x1="0" y1="1" x2="0" y2="0">
        {stop("0", "var(--lamp)")}
        {stop(".55", "var(--cream)")}
        {stop("1", "#fff")}
      </linearGradient>
      <linearGradient id={`dim${uid}`} x1="0" y1="1" x2="0" y2="0">
        {stop("0", "oklch(0.25 0.006 60)")}
        {stop("1", "oklch(0.52 0.008 60)")}
      </linearGradient>
      <linearGradient id={`dimdown${uid}`} x1="0" y1="0" x2="0" y2="1">
        {stop("0", "oklch(0.38 0.007 60)")}
        {stop("1", "oklch(0.22 0.005 60)")}
      </linearGradient>
      <linearGradient id={`loss${uid}`} x1="0" y1="1" x2="0" y2="0">
        {stop("0", "oklch(0.45 0.14 27)")}
        {stop("1", "var(--loss)")}
      </linearGradient>
      <pattern id={`hatch${uid}`} width="4" height="4" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">
        <rect width="4" height="4" style={{ fill: "oklch(0.19 0.005 60)" }} />
        <rect width="1.3" height="4" style={{ fill: "oklch(0.44 0.008 60)" }} />
      </pattern>
      <pattern id={`stripe${uid}`} width="5" height="5" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">
        <rect width="1.4" height="5" style={{ fill: "oklch(1 0 0 / .28)" }} />
      </pattern>
      <filter id={`glow${uid}`} x="-60%" y="-60%" width="220%" height="220%">
        <feGaussianBlur stdDeviation="5" result="b" />
        <feMerge>
          <feMergeNode in="b" />
          <feMergeNode in="SourceGraphic" />
        </feMerge>
      </filter>
    </defs>
  );
}

/** The axis-label text style charts.js repeats (`font-size:…;fill:var(--fg-subtle);font-family:var(--font)`). */
export const subtleText = (fontSize: string): CSSProperties => ({
  fontSize,
  fill: "var(--fg-subtle)",
  fontFamily: "var(--font)",
});
